# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-01 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=2048)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('top_image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('top_image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='news/top_images/')),
                ('details', models.TextField(blank=True, null=True)),
                ('authors', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[set([1, 'Real News']), set([2, 'Spam News'])], default=1)),
                ('crawled', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
