# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_engine', '0003_auto_20180401_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetail',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
