# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-26 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_engine', '0004_auto_20180405_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeNewsTrainingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=2048)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Real News'), (2, 'Fake News')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='newsdetail',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Real News'), (2, 'Fake News')], default=1),
        ),
    ]
