# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-26 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_engine', '0005_auto_20180626_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakenewstrainingmodel',
            name='crawled',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fakenewstrainingmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fakenewstrainingmodel',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fakenewstrainingmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
